Update veracode-policy-scan.yml

diff --git a/.github/workflows/veracode-policy-scan.yml b/.github/workflows/veracode-policy-scan.yml
--- a/.github/workflows/veracode-policy-scan.yml
+++ b/.github/workflows/veracode-policy-scan.yml
@@ -120,37 +120,44 @@ jobs:
           sandboxname: GitHub App Scans-${{ github.event.client_payload.user_config.sandbox_scan.branch }}
 
   code-scanning-alert:
-    needs: policy_scan
-    runs-on: ubuntu-latest
-    if: ${{ inputs.create_code_scanning_alert && always() }}
-    name: Create code scanning alerts
-    steps:
-      - name: Checkout Target Repository
-        uses: actions/checkout@v4
-        with:
-          repository: ${{ inputs.owner }}/QuatarFlaws
-          token: ${{ inputs.token }}
-          path: target-repo
+  needs: policy_scan
+  runs-on: ubuntu-latest
+  if: ${{ inputs.create_code_scanning_alert && always() }}
+  name: Create code scanning alerts
+  steps:
+    - name: Checkout Target Repository
+      uses: actions/checkout@v4
+      with:
+        repository: ${{ inputs.owner }}/QuatarFlaws
+        token: ${{ inputs.token }}
+        path: target-repo
 
-      - name: Convert policy scan output to SARIF format for java language
-        if: ${{ inputs.language == 'Java' }}
-        uses: Veracode/veracode-pipeline-scan-results-to-sarif@v2.0.3
-        with:
-          scan-type: policy
-          results-json: 'target-repo/policy_flaws.json'
-          output-results-sarif: veracode-results.sarif
-          repo_owner: ${{ inputs.owner }}
-          repo_name: ${{ inputs.repo }}
-          commitSHA: ${{ inputs.sha }}
-          ref: ${{ inputs.ref }}
-          githubToken: ${{ inputs.token }}
-          source-base-path-1: 'com/:src/main/java/com/'
-          source-base-path-2: 'WEB-INF:src/main/webapp/WEB-INF'
+    - name: Validate policy_flaws.json
+      run: |
+        if [ ! -f target-repo/policy_flaws.json ]; then
+          echo "Error: policy_flaws.json not found in the target repository."
+          exit 1
+        fi
 
-      - name: Convert policy scan output to SARIF format for non java language
-        if: ${{ inputs.language != 'Java' }}
-        uses: Veracode/veracode-pipeline-scan-results-to-sarif@v2.0.3
-        with:
+    - name: Convert policy scan output to SARIF format for Java language
+      if: ${{ inputs.language == 'Java' }}
+      uses: Veracode/veracode-pipeline-scan-results-to-sarif@v2.0.3
+      with:
+        scan-type: policy
+        results-json: 'target-repo/policy_flaws.json'
+        output-results-sarif: veracode-results.sarif
+        repo_owner: ${{ inputs.owner }}
+        repo_name: ${{ inputs.repo }}
+        commitSHA: ${{ inputs.sha }}
+        ref: ${{ inputs.ref }}
+        githubToken: ${{ inputs.token }}
+        source-base-path-1: 'com/:src/main/java/com/'
+        source-base-path-2: 'WEB-INF:src/main/webapp/WEB-INF'
+
+    - name: Convert policy scan output to SARIF format for non java language
+      if: ${{ inputs.language != 'Java' }}
+      uses: Veracode/veracode-pipeline-scan-results-to-sarif@v2.0.3
+      with:
           scan-type: policy
           results-json: '/tmp/policy_flaws.json'
           output-results-sarif: veracode-results.sarif
